import type { Metadata } from "next";
import AdminLayout from "./layout/AdminLayout";

export const metadata: Metadata = {
  title: "GYM Class Schedule",
  description: "Generated by @KJ-RahiiL",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div>
      <AdminLayout>{children}</AdminLayout>
    </div>
  );
}
